// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZtL5-rQLiiYGAmX7AeIg09iKi3VkyzdU',
    appId: '1:405210769162:web:2be0a07bc1c792852f7cf3',
    messagingSenderId: '405210769162',
    projectId: 'makeaword-dfac0',
    authDomain: 'makeaword-dfac0.firebaseapp.com',
    storageBucket: 'makeaword-dfac0.appspot.com',
    measurementId: 'G-07L5H3ZDGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkiLy2QhBPDUjwrSXlWbV4zNHBhf89iuM',
    appId: '1:405210769162:android:376378912b1697772f7cf3',
    messagingSenderId: '405210769162',
    projectId: 'makeaword-dfac0',
    storageBucket: 'makeaword-dfac0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBljn-F6dT6_ITmiOF76aD1nLJKkLPR6ww',
    appId: '1:405210769162:ios:04503c4fab8827f92f7cf3',
    messagingSenderId: '405210769162',
    projectId: 'makeaword-dfac0',
    storageBucket: 'makeaword-dfac0.appspot.com',
    iosBundleId: 'com.example.makeAWord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBljn-F6dT6_ITmiOF76aD1nLJKkLPR6ww',
    appId: '1:405210769162:ios:2a241b07202cdd322f7cf3',
    messagingSenderId: '405210769162',
    projectId: 'makeaword-dfac0',
    storageBucket: 'makeaword-dfac0.appspot.com',
    iosBundleId: 'com.example.makeAWord.RunnerTests',
  );
}
